[package]
name = "steamcardwalldl"
version = "0.1.0"
authors = ["Mike <michaelpulliam1@gmail.com>"]

[dependencies]
select = "0.4.2"
reqwest = "0.8.5"
clap = {version = "2.31", features = ["yaml"]}
url = "1.7"